// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'helpIcon': string;
  'slider': string;
  'sliderTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
