name: Backend

on:
  push:
    branches: [master]
    paths:
      - backend/**
      - shared/**
      - .github/workflows/backend.yml
  pull_request:
    branches: [master]
    paths:
      - backend/**
      - shared/**
      - .github/workflows/backend.yml

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-18.04]
        node: [12]

    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('backend/package-lock.json') }}
      - name: Install node_modules
        run: npm ci
        working-directory: backend
      - name: Lint
        run: npm run lint
        working-directory: backend
      - name: Type check
        run: npm run lint:ts
        working-directory: backend
      - name: Unit test
        run: npm run test
        working-directory: backend
      - name: Build
        run: npm run build
        working-directory: backend
      - name: Start docker image
        if: matrix.os != 'windows-latest'
        run: docker-compose up -d
        working-directory: backend
      - name: Test database connection
        if: matrix.os != 'windows-latest'
        run: |
          npm run init-db
          npm run init-db:dev
        working-directory: backend
