name: Frontend

on:
  push:
    branches: [master]
    paths:
      - frontend/**
      - .github/workflows/frontend.yml
  pull_request:
    branches: [master]
    paths:
      - frontend/**
      - .github/workflows/frontend.yml

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-18.04]
        node: [12]

    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
      - name: Install node_modules
        run: npm ci
        working-directory: frontend
      - name: Format
        run: npm run format
        working-directory: frontend
      - name: Lint
        run: npm run lint
        working-directory: frontend
      - name: Type check
        run: npm run lint:ts
        working-directory: frontend
      - name: Unit test
        run: npm run test
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: frontend
